version: '3.9'
services:
  mosquitto:
    image: eclipse-mosquitto:2.0.20
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/certs:/mosquitto/certs
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - water_meter_net

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=water_org
      - DOCKER_INFLUXDB_INIT_BUCKET=water_bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mysecrettoken
    networks:
      - water_meter_net

  api:
    build: ./api
    container_name: api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mosquitto
      - influxdb
    networks:
      - water_meter_net
    volumes:
      - ./mosquitto/certs:/mosquitto/certs

  frontend:
    image: nginx:latest
    container_name: frontend
    restart: always
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    networks:
      water_meter_net:
        ipv4_address: 172.30.0.3

networks:
  water_meter_net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.30.0.0/16"
